name: VPS Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build Svelte App
      run: |
        npm install
        npm run build
    - name: Copy to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        rm: true
        source: "build/*"
        target: "${{ secrets.TARGET }}"